#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {MODEL_NAME}-deployment
spec:
  selector:
    matchLabels:
      app: {MODEL_NAME}-server
  replicas: 1
  template:
    metadata:
      labels:
        app: {MODEL_NAME}-server
    spec:
      containers:
      - name: {MODEL_NAME}-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/{DOCKER_USER}/{MODEL_NAME}:{github.sha}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {MODEL_NAME}-service
  name: {MODEL_NAME}-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: {MODEL_NAME}-server
  type: LoadBalancer
