#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/carla1072/node-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: api-service
  name: api-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: api-server
  type: LoadBalancer
